All:
	g++ -O3 -o alignment_handler_multi test_handler.cpp JunctionHandler.cpp SpliceWay.cpp SamRec.cpp sharedlib.cpp AlignmentHandler.cpp JunctionSeed.cpp UnionExpressedRegions.cpp disjointset.cpp -lpthread 2>log

