All:
	#g++ -O3 -o generate_fusiongene_convert_coordinate generate_fusiongene_convert_coordinate.cpp JunctionSeed.cpp SamRec.cpp sharedlib.cpp SpliceWay.cpp

	g++ -O3 -o generate_fusiongene_convert_coordinate_trim generate_fusiongene_convert_coordinate_trim.cpp JunctionSeed.cpp SamRec.cpp sharedlib.cpp SpliceWay.cpp

	g++ -O3 -o generate_fusiongene_convert_coordinate_trim_dRanger generate_fusiongene_convert_coordinate_trim_dRanger.cpp JunctionSeed.cpp SamRec.cpp sharedlib.cpp SpliceWay.cpp




